### ISSUE TITLE
GenerateLibrariesXml broken in 1.4

### ISSUE THREAD

**Issue by bkolb** [mbeddr/mps-gradle-plugin#60]
The GenerateLibrariesXml throws an exception in 1.4 if the overrides files does not exist.
It used to work in 1.2

```
org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':generateLibrariesXml'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:72)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
Caused by: org.gradle.api.InvalidUserDataException: File '/Users/xxxxx/projectlibraries.overrides.properties' specified for property 'overrides' does not exist.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:69)
        ... 34 more
```

**Comment by bkolb** [comment]
gradlew --version gives me this:

`$ ./gradlew --version

------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.5 (AdoptOpenJDK 11.0.5+10)
OS:           Mac OS X 10.15.3 x86_64`

**Comment by till-f** [comment]
Thanks! Came across the same problem with mps-gradle-plugin 1.0.55 after upgrading to gradle 5.6.2. Also upgraded mps-gradle-plugin to 1.4, which didn't solve it. Would have never tried 1.2 without this ticket.
