### ISSUE TITLE
cannot run plugin in headless environment

### ISSUE THREAD

**Issue by amirmv2006** [mbeddr/mps-gradle-plugin#95]
I want to use this gradle plugin to define code generation for my models as part of a CI job, but I noticed it doesn't work because somehow the MPS which is executed is not completely in headless mode. To showcase the problem, I have created this small project snippet, and as you [can see](https://github.com/amirmv2006/mammad-zargar/runs/2166279970?check_suite_focus=true#step:5:64), github's workflow actions are failing with the same error:
```log
> Task :generate
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
initialising environment
Creating IDEA environment
Creating IdeaCmdApplication
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil (file:/home/runner/work/mammad-zargar/mammad-zargar/build/mps/lib/util.jar) to field java.io.DeleteOnExitHook.files
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
generation failed
error generating
java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
	at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:231)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
	at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1494)
	at java.desktop/java.awt.EventQueue.isDispatchThread(EventQueue.java:1086)
	at com.intellij.testFramework.TestApplicationManager$Companion$createInstance$2.invoke(TestApplicationManager.kt:120)
	at com.intellij.testFramework.TestApplicationManager$Companion$createInstance$2.invoke(TestApplicationManager.kt:72)
	at com.intellij.SimpleApplicationBootstrapperKt.doLoadApp(simpleApplicationBootstrapper.kt:44)
	at com.intellij.testFramework.TestApplicationManager$Companion.createInstance(TestApplicationManager.kt:119)
	at com.intellij.testFramework.TestApplicationManager$Companion.getInstance(TestApplicationManager.kt:87)
	at com.intellij.testFramework.TestApplicationManager.getInstance(TestApplicationManager.kt)
	at jetbrains.mps.tool.environment.IdeaEnvironment.createIdeaApplication(IdeaEnvironment.java:200)
	at jetbrains.mps.tool.environment.IdeaEnvironment.init(IdeaEnvironment.java:86)
	at de.itemis.mps.gradle.project.loader.LoaderKt.executeWithProject(Loader.kt:109)
	at de.itemis.mps.gradle.project.loader.LoaderKt.executeWithProject(Loader.kt:156)
	at de.itemis.mps.gradle.generate.MainKt$main$1.invoke(Main.kt:24)
	at de.itemis.mps.gradle.generate.MainKt$main$1.invoke(Main.kt)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at de.itemis.mps.gradle.generate.MainKt.main(Main.kt:18)
```
Am I missing a configuration [here](https://github.com/amirmv2006/mammad-zargar/blob/master/build.gradle.kts)? Any guidance would be appreciated! I'm fine with hotfixes also :smile:

**Comment by sergej-koscejev** [comment]
We run Xvfb on our CI machines. I don't have an explanation regarding what requires it and why but it works that way.
